filebeat.inputs:
- type: filestream
  id: system-logs
  enabled: true
  paths:
    - /var/log/auth.log
    - /var/log/syslog

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"